### ISSUE TITLE
Related objects are not loaded when visiting item page from list page

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#13]
When you visit `https://pithos.synnefo.live/ui/containers/` and then visit
`https://pithos.synnefo.live/ui/containers/pithos`, pithos' objects are not loaded.
However, when you visit directly the page `https://pithos.synnefo.live/ui/containers/pithos` all objects are visible

**Comment by olgabrani** [comment]
When visiting the item's route coming from the items' route, there is no new call to fetch the item's details...

**Comment by vinilios** [comment]
That is the default ember behaviour. Since the container details are already loaded in the container list route, container details route won't try to reload those details unless said so explicitly. The issue appears due to the fact that container details response differ between the containers list API call (no container objects list in response) and the container details API call (objects appear in response).

A workaround is to reload the container object every time the container details route gets activated 

``` javascript
export default Ember.Route.extend({
  setupController: function(controller, model) {
    model.reload();
    this._super(controller, model);
  }
});
```
