### ISSUE TITLE
Container delete bug

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#14]
Adapter's deleteRecord is not called.
### Working case
- Create a container
- Verify that it has been created running 'kamaki container list'
- Refresh the page
- Delete the container
- Verify from console logs that a "DELETE" call has been send
### How to reproduce this bug
- Create a container 
- Verify that it has been created running 'kamaki container list'
- Delete this container without refreshing the page
- Check that no "DELETE" call has been send

**Comment by vinilios** [comment]
It seems that the delete is not properly propagated to the adapter due to the fact that newly created container models remain in `created.uncommitted` state. After a bit of debugging i noticed that model's 
save() promise is not getting resolved properly. This seems to occur due to the emptyness of the pithos API response in create call while adapter's createRecord ajax promise excepts 'json' data in response. I guess empty response is not a valid json object.

**Comment by olgabrani** [comment]
I guess this has accidentally been fixed [here](https://github.com/olgabrani/synnefo/blob/96d648af53a39439dfe1fb9045eb480580c6dcf3/snf-ui-app/ui-web/app/adapters/container.js#L44)
