### ISSUE TITLE
Tooltip doesn't hide if you change route

### ISSUE THREAD

**Issue by athinab** [olgabrani/synnefo#167]
Hover over (!!) a dir in objects view and then click its name in order to see its content. 

Reported by @erethon!

**Comment by olgabrani** [comment]
I noticed a strange tooltip behaviour:
If you visit the containers route in grid view and hover the date info, you get a nice tooltip.
If you switch to list view however, the nicely formatted tooltip is not visible.
If you reload the models or the page, it works ok again.
The same happens if you go from list view to grid view.
