### ISSUE TITLE
Download link for objects is not working

### ISSUE THREAD

**Issue by olgabrani** [olgabrani/synnefo#96]
Any ideas why?

The produced html code is 
`<a href="https://pithos.synnefo.live/pithos/ui/view/uuid/pithos/file.jpg" data-bindattr-1559="1559" title="download Item" download=""><i class="fa fa-download"></i></a>`

**Comment by vinilios** [comment]
I thinks its due to the fact that pithos download urls are not trusted in you environment,

as noted [here](https://html.spec.whatwg.org/multipage/semantics.html#downloading-resources):
This algorithm is intended to mitigate security dangers involved in downloading files from untrusted sites, and user agents are strongly urged to follow it.

How about completely removing the `download` attr ?
